[api]
enabled = true
port = 54321
schemas = ["public"]

[db]
port = 54322

[functions.verify-company-type]
verify_jwt = false

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.check-availability]
verify_jwt = false

[functions.log-interaction]
verify_jwt = false

[functions.admin-data]
verify_jwt = false
